name: simulamaiscnh
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_masked_text: ^0.8.0
  intl: ^0.16.1
  flutter_speed_dial: ^1.2.5
  sqflite: ^1.3.0
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #IMAGENS
      - assets/imagens/questoes.png
      - assets/imagens/placas.png
      - assets/imagens/progresso.png
      - assets/imagens/simulados.png
      - assets/imagens/background.png
    
    #PLACAS
      - assets/imagens/questions/a1a.jpg
      - assets/imagens/questions/a1b.jpg
      - assets/imagens/questions/a2a.jpg
      - assets/imagens/questions/a2b.jpg
      - assets/imagens/questions/a3a.jpg
      - assets/imagens/questions/a3b.jpg
      - assets/imagens/questions/a4a.jpg
      - assets/imagens/questions/a4b.jpg
      - assets/imagens/questions/a5a.jpg
      - assets/imagens/questions/a5b.jpg
      - assets/imagens/questions/a6.jpg
      - assets/imagens/questions/a7a.jpg
      - assets/imagens/questions/a7b.jpg
      - assets/imagens/questions/a8.jpg
      - assets/imagens/questions/a9.jpg
      - assets/imagens/questions/a10a.jpg
      - assets/imagens/questions/a10b.jpg
      - assets/imagens/questions/a11a.jpg
      - assets/imagens/questions/a11b.jpg
      - assets/imagens/questions/a12.jpg
      - assets/imagens/questions/a13a.jpg
      - assets/imagens/questions/a13b.jpg
      - assets/imagens/questions/a14.jpg
      - assets/imagens/questions/a15.jpg
      - assets/imagens/questions/a16.jpg
      - assets/imagens/questions/a17.jpg
      - assets/imagens/questions/a18.jpg
      - assets/imagens/questions/a19.jpg
      - assets/imagens/questions/a20a.jpg
      - assets/imagens/questions/a20b.jpg
      - assets/imagens/questions/a21a.jpg
      - assets/imagens/questions/a21b.jpg
      - assets/imagens/questions/a21c.jpg
      - assets/imagens/questions/a21d.jpg
      - assets/imagens/questions/a21e.jpg
      - assets/imagens/questions/a22.jpg
      - assets/imagens/questions/a23.jpg
      - assets/imagens/questions/a24.jpg
      - assets/imagens/questions/a25.jpg
      - assets/imagens/questions/a26a.jpg
      - assets/imagens/questions/a26b.jpg
      - assets/imagens/questions/a27.jpg
      - assets/imagens/questions/a28.jpg
      - assets/imagens/questions/a29.jpg
      - assets/imagens/questions/a30a.jpg
      - assets/imagens/questions/a30b.jpg
      - assets/imagens/questions/a30c.jpg
      - assets/imagens/questions/a31.jpg
      - assets/imagens/questions/a32a.jpg
      - assets/imagens/questions/a32b.jpg
      - assets/imagens/questions/a33a.jpg
      - assets/imagens/questions/a33b.jpg
      - assets/imagens/questions/a34.jpg
      - assets/imagens/questions/a35.jpg
      - assets/imagens/questions/a36.jpg
      - assets/imagens/questions/a37.jpg
      - assets/imagens/questions/a38.jpg
      - assets/imagens/questions/a39.jpg
      - assets/imagens/questions/a40.jpg
      - assets/imagens/questions/a41.jpg
      - assets/imagens/questions/a42a.jpg
      - assets/imagens/questions/a42b.jpg
      - assets/imagens/questions/a42c.jpg
      - assets/imagens/questions/a43.jpg
      - assets/imagens/questions/a44.jpg
      - assets/imagens/questions/a45.jpg
      - assets/imagens/questions/a46.jpg
      - assets/imagens/questions/a47.jpg
      - assets/imagens/questions/a48.jpg
      - assets/imagens/questions/i11.jpg
      - assets/imagens/questions/i12.jpg
      - assets/imagens/questions/i13.jpg
      - assets/imagens/questions/i14.jpg
      - assets/imagens/questions/i15.jpg
      - assets/imagens/questions/i16.jpg
      - assets/imagens/questions/i17.jpg
      - assets/imagens/questions/i18.jpg
      - assets/imagens/questions/i19.jpg
      - assets/imagens/questions/i20.jpg
      - assets/imagens/questions/i21.jpg
      - assets/imagens/questions/i22.jpg
      - assets/imagens/questions/i23.jpg
      - assets/imagens/questions/r1.jpg
      - assets/imagens/questions/r3.jpg
      - assets/imagens/questions/r4a.jpg
      - assets/imagens/questions/r4b.jpg
      - assets/imagens/questions/r5.jpg
      - assets/imagens/questions/r6a.jpg
      - assets/imagens/questions/r6b.jpg
      - assets/imagens/questions/r6c.jpg
      - assets/imagens/questions/r7.jpg
      - assets/imagens/questions/r8.jpg
      - assets/imagens/questions/r9.jpg
      - assets/imagens/questions/r10.jpg
      - assets/imagens/questions/r11.jpg
      - assets/imagens/questions/r12.jpg
      - assets/imagens/questions/r13.jpg
      - assets/imagens/questions/r14.jpg
      - assets/imagens/questions/r15.jpg
      - assets/imagens/questions/r16.jpg
      - assets/imagens/questions/r17.jpg
      - assets/imagens/questions/r18.jpg
      - assets/imagens/questions/r19.jpg
      - assets/imagens/questions/r20.jpg
      - assets/imagens/questions/r21.jpg
      - assets/imagens/questions/r22.jpg
      - assets/imagens/questions/r23.jpg
      - assets/imagens/questions/r24a.jpg
      - assets/imagens/questions/r24b.jpg
      - assets/imagens/questions/r25a.jpg
      - assets/imagens/questions/r25b.jpg
      - assets/imagens/questions/r25c.jpg
      - assets/imagens/questions/r25d.jpg
      - assets/imagens/questions/r26.jpg
      - assets/imagens/questions/r27.jpg
      - assets/imagens/questions/r28.jpg
      - assets/imagens/questions/r29.jpg
      - assets/imagens/questions/r30.jpg
      - assets/imagens/questions/r31.jpg
      - assets/imagens/questions/r32.jpg
      - assets/imagens/questions/r33.jpg
      - assets/imagens/questions/r34.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
